AWSTemplateFormatVersion: '2010-09-09'
Description: "StackSet example to create an S3 bucket in multiple accounts"

Parameters:
  BucketName:
    Type: String
    Description: "Name of the S3 bucket"
    Default: "my-default-bucket-123777745"

Resources:
  ExampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
