AWSTemplateFormatVersion: '2010-09-09'
Description: Full Production Stack: VPC + Compute + Deployment + CI/CD

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  GitHubOwner:
    Type: String
  GitHubRepo:
    Type: String
  GitHubBranch:
    Type: String
    Default: main
  GitHubToken:
    Type: String
    NoEcho: true

Resources:
  # 1️⃣ VPC
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr

  # 2️⃣ Subnets & NAT
  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./subnets.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Cidr: 10.0.1.0/24
        PublicSubnet2Cidr: 10.0.2.0/24
        PrivateSubnet1Cidr: 10.0.3.0/24
        PrivateSubnet2Cidr: 10.0.4.0/24

  # 3️⃣ Security Groups
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sg.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  # 4️⃣ Compute (ALB + ASG)
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./compute.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnets: !GetAtt SubnetStack.Outputs.PublicSubnets
        PrivateSubnets: !GetAtt SubnetStack.Outputs.PrivateSubnets
        WebSG: !GetAtt SecurityGroupStack.Outputs.WebSGId

  # 5️⃣ CodeDeploy Application & Deployment Group
  DeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./deploy.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        ASGName: !GetAtt ComputeStack.Outputs.ASG
        ALBTargetGroupARN: !GetAtt ComputeStack.Outputs.TargetGroup

  # 6️⃣ CI/CD Pipeline
  PipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./pipeline.yaml
      Parameters:
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        GitHubToken: !Ref GitHubToken
        CodeDeployApplication: !GetAtt DeployStack.Outputs.WebApp
        CodeDeployDeploymentGroup: !GetAtt DeployStack.Outputs.WebDeploymentGroup

Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
  PublicSubnets:
    Value: !GetAtt SubnetStack.Outputs.PublicSubnets
  PrivateSubnets:
    Value: !GetAtt SubnetStack.Outputs.PrivateSubnets
  WebSG:
    Value: !GetAtt SecurityGroupStack.Outputs.WebSGId
  ALBDNS:
    Value: !GetAtt ComputeStack.Outputs.ALB
  ASG:
    Value: !GetAtt ComputeStack.Outputs.ASG
  CodeDeployApplication:
    Value: !GetAtt DeployStack.Outputs.WebApp
  CodeDeployDeploymentGroup:
    Value: !GetAtt DeployStack.Outputs.WebDeploymentGroup
  PipelineName:
    Value: !Ref PipelineStack
