AWSTemplateFormatVersion: '2010-09-09'
Description: Parent Stack for Production-ready VPC

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR for VPC

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr

  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./subnets.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Cidr: 10.0.1.0/24
        PublicSubnet2Cidr: 10.0.2.0/24
        PrivateSubnet1Cidr: 10.0.3.0/24
        PrivateSubnet2Cidr: 10.0.4.0/24

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sg.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
