AWSTemplateFormatVersion: '2010-09-09'
Description: Parent Stack for Production-ready VPC + Compute

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr

  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./subnets.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Cidr: 10.0.1.0/24
        PublicSubnet2Cidr: 10.0.2.0/24
        PrivateSubnet1Cidr: 10.0.3.0/24
        PrivateSubnet2Cidr: 10.0.4.0/24

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sg.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./compute.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnets: !GetAtt SubnetStack.Outputs.PublicSubnets
        PrivateSubnets: !GetAtt SubnetStack.Outputs.PrivateSubnets
        WebSG: !GetAtt SecurityGroupStack.Outputs.WebSGId

Outputs:
  VpcId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId

  PublicSubnets:
    Description: Public Subnet IDs
    Value: !GetAtt SubnetStack.Outputs.PublicSubnets

  PrivateSubnets:
    Description: Private Subnet IDs
    Value: !GetAtt SubnetStack.Outputs.PrivateSubnets

  WebSecurityGroup:
    Description: Web Security Group ID
    Value: !GetAtt SecurityGroupStack.Outputs.WebSGId

  ALBDNS:
    Description: Application Load Balancer DNS
    Value: !GetAtt ComputeStack.Outputs.ALB

  TargetGroupARN:
    Description: ALB Target Group ARN
    Value: !GetAtt ComputeStack.Outputs.TargetGroup

  AutoScalingGroupName:
    Description: Web Auto Scaling Group Name
    Value: !GetAtt ComputeStack.Outputs.ASG
