AWSTemplateFormatVersion: '2010-09-09'
Description: Full Production Stack- VPC + Compute + Deployment (StackSet-ready)

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16

Resources:
  # 1️⃣ VPC
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-stackset-templates.s3.amazonaws.com/vpc.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr

  # 2️⃣ Subnets & Route Tables
  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-stackset-templates.s3.amazonaws.com/subnets.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Cidr: 10.0.1.0/24
        PublicSubnet2Cidr: 10.0.2.0/24
        PrivateSubnet1Cidr: 10.0.3.0/24
        PrivateSubnet2Cidr: 10.0.4.0/24

  # 3️⃣ Security Groups
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-stackset-templates.s3.amazonaws.com/sg.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  # 4️⃣ Compute: ALB + Auto Scaling Group
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-stackset-templates.s3.amazonaws.com/compute.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnets: !GetAtt SubnetStack.Outputs.PublicSubnets
        PrivateSubnets: !GetAtt SubnetStack.Outputs.PrivateSubnets
        WebSG: !GetAtt SecurityGroupStack.Outputs.WebSGId

  # 5️⃣ CodeDeploy Application & Deployment Group
  DeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://my-stackset-templates.s3.amazonaws.com/deploy.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        ASGName: !GetAtt ComputeStack.Outputs.ASG
        ALBTargetGroupARN: !GetAtt ComputeStack.Outputs.TargetGroup

Outputs:
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
  PublicSubnets:
    Value: !GetAtt SubnetStack.Outputs.PublicSubnets
  PrivateSubnets:
    Value: !GetAtt SubnetStack.Outputs.PrivateSubnets
  WebSG:
    Value: !GetAtt SecurityGroupStack.Outputs.WebSGId
  ALBDNS:
    Value: !GetAtt ComputeStack.Outputs.ALB
  ASG:
    Value: !GetAtt ComputeStack.Outputs.ASG
  CodeDeployApplication:
    Value: !GetAtt DeployStack.Outputs.WebApp
  CodeDeployDeploymentGroup:
    Value: !GetAtt DeployStack.Outputs.WebDeploymentGroup
