AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Stack

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ProductionVPC

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref MyVPC
