AWSTemplateFormatVersion: '2010-09-09'
Description: ALB + Auto Scaling Group

Parameters:
  VpcId:
    Type: String
  PublicSubnets:
    Type: CommaDelimitedList
  PrivateSubnets:
    Type: CommaDelimitedList
  WebSG:
    Type: String

Resources:
  # Security group for ALB
  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB SG allowing HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # Application Load Balancer
  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: AppLB
      Scheme: internet-facing
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref ALBSG

  # Target Group
  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPort: 80
      HealthCheckPath: /

  # Listener
  AppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AppLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup

  # Launch Template
  WebLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: WebLaunchTemplate
      LaunchTemplateData:
        InstanceType: t3.micro
        ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2
        SecurityGroupIds:
          - !Ref WebSG
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl enable httpd
            systemctl start httpd
            echo "Hello from EC2" > /var/www/html/index.html

  # Auto Scaling Group
  WebASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref PrivateSubnets
      LaunchTemplate:
        LaunchTemplateId: !Ref WebLaunchTemplate
        Version: !GetAtt WebLaunchTemplate.LatestVersionNumber
      MinSize: 2
      MaxSize: 4
      DesiredCapacity: 2
      TargetGroupARNs:
        - !Ref AppTargetGroup
      HealthCheckType: EC2
      HealthCheckGracePeriod: 60

Outputs:
  ALB:
    Value: !Ref AppLoadBalancer
  TargetGroup:
    Value: !Ref AppTargetGroup
  ASG:
    Value: !Ref WebASG
