AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC StackSet Example"

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: "CIDR block for the VPC"

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "StackSet-VPC-${AWS::AccountId}"
  
Outputs:
  VpcId:
    Description: "VPC ID"
    Value: !Ref MyVPC
