AWSTemplateFormatVersion: '2010-09-09'
Description: Root StackSet - deploys VPC, ALB/ASG, and CodeDeploy

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<S3_BUCKET>/vpc-stack.yaml
      Parameters:
        VpcCidr: 10.0.0.0/16
        PublicSubnet1Cidr: 10.0.1.0/24
        PublicSubnet2Cidr: 10.0.2.0/24
        PrivateSubnet1Cidr: 10.0.3.0/24
        PrivateSubnet2Cidr: 10.0.4.0/24
        AvailabilityZone1: !Select [0, !GetAZs ""]
        AvailabilityZone2: !Select [1, !GetAZs ""]

  ALBASGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<S3_BUCKET>/alb-asg-stack.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        KeyName: <EC2_KEY_PAIR>
        InstanceType: t3.micro
        AmiId: <AMI_ID>

  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://<S3_BUCKET>/codedeploy-stack.yaml
      Parameters:
        DevASG: !GetAtt ALBASGStack.Outputs.DevASG
        ProdASG: !GetAtt ALBASGStack.Outputs.ProdASG
        DevRole: arn:aws:iam::<DEV_ACCOUNT_ID>:role/CodeDeployEC2RoleDev
        ProdRole: arn:aws:iam::<PROD_ACCOUNT_ID>:role/CodeDeployEC2RoleProd
